# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Simple3DGame' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Simple3DGame
  pod 'Firebase/Analytics'
  pod 'lottie-ios'

end
